backend:
  name: git-gateway
  repo: alifgiant/motion_mis
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: "src/images"
public_folder: "/images/uploads"

collections:
  - name: "generation-collection"
    label: "Generation"
    folder: "content/generation"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: string}
      - {label: "Description", name: "description", widget: string}
  - name: "member-collection"
    label: "Member"
    folder: "content/member"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "LinkedIn", name: "linkedin", widget: string}
      - {label: "Generation", name: "description", widget: string}