name: CI

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-member:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Setup chrome driver
      - uses: nanasess/setup-chromedriver@master
      - name: Check Dependency
        run: |
          which chromedriver
          which python3
          which pip3
      
      # Install Python Deps
      - name: Install Python Deps
        run: pip3 install -r requirements.txt

      # Run Python Scrapper
      - name: Run Python Scrapper
        env: # Or as an environment variable
          LINKEDIN_EMAIL: ${{ secrets.LINKEDIN_EMAIL }}
          LINKEDIN_PASS: ${{ secrets.LINKEDIN_PASS }}
        run: |
          chmod +x ./build_member.sh
          ./build_member.sh
      
      # archive result
      - name: Archive Crawl Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: linkedin-result
          path: members_data_generated
  build-web:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build-member

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Download Crawl Artifacts
        uses: actions/download-artifact@v2
        with:
          name: linkedin-result
      
      # Setup Flutter
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          
      # Build Flutter Web
      - name: Build Flutter Web
        run: |
          chmod +x ./build_web.sh
          ./build_web.sh
